version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonar
    volumes: [pg_data:/var/lib/postgresql/data]

  sonarqube:
    image: sonarqube:community
    depends_on: [postgres]
    ports: ["9000:9000"]
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpass
    volumes: [sonar_data:/opt/sonarqube/data, sonar_extensions:/opt/sonarqube/extensions]

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports: ["8080:8080"]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # for building images inside Jenkins
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true

volumes:
  pg_data:
  sonar_data:
  sonar_extensions:
  jenkins_home: